### We're now going to repeat step 2 of the manual QC, but for 100-year events. Hopefully the worst offenders have already been removed at the 1000-year step, but we still want to look through the maps for these

#### Start at 72h, then do 48, then 24 for each year

In [1]:
import pandas as pd
import os

In [298]:
duration = 24
dataset = "prism" ### which dataset to analyze

year = 2001

workdir = "/glade/work/rschumac/precip_data/extremerain/"

#### read in the exceedance files into pandas dataframes - note that now we're reading in the cleaned, edited files

In [299]:
df100_72h = pd.read_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h_edit.csv")
df10_72h = pd.read_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h_edit.csv")
try:
    df1000_72h = pd.read_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h_edit.csv")
except:  ## if no rows, just make an empty dataframe with the right columns
    df1000_72h = pd.DataFrame(columns=df_72h.columns)

### and the 48-h ones
df100_48h = pd.read_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h_edit.csv")
df10_48h = pd.read_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h_edit.csv")
try:
    df1000_48h = pd.read_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h_edit.csv")
except:
    df1000_48h = pd.DataFrame(columns=df_48h.columns)

### and the 24-h ones
df100_24h = pd.read_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h_edit.csv")
df10_24h = pd.read_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h_edit.csv")
try:
    df1000_24h = pd.read_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h_edit.csv")
except:
    df1000_24h = pd.DataFrame(columns=df_48h.columns)

In [300]:
### change this to match the duration...
df100_24h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2001-01-27 12:00:00,33.458333,-109.750000,96.281,4.483180,1.048838,0
1,2001-01-27 12:00:00,33.500000,-109.750000,93.628,0.235663,1.002523,0
2,2001-03-06 12:00:00,34.708333,-120.000000,212.566,13.968608,1.070336,0
3,2001-03-06 12:00:00,34.708333,-119.958333,247.117,32.070928,1.149135,0
4,2001-03-06 12:00:00,34.708333,-119.916667,248.282,2.363965,1.009613,0
5,2001-03-06 12:00:00,34.750000,-120.041667,201.025,5.164381,1.026368,0
6,2001-03-06 12:00:00,34.750000,-120.000000,214.612,15.474478,1.077707,0
7,2001-03-06 12:00:00,34.750000,-119.958333,223.350,17.816137,1.086682,0
8,2001-03-06 12:00:00,34.958333,-120.000000,192.328,13.993071,1.078465,0
9,2001-03-06 12:00:00,34.958333,-119.958333,202.796,16.222493,1.086950,0
10,2001-03-06 12:00:00,35.000000,-120.041667,177.071,4.183642,1.024199,0
11,2001-03-06 12:00:00,35.000000,-120.000000,195.276,19.319025,1.109794,0
12,2001-03-06 12:00:00,35.041667,-120.041667,167.784,2.529861,1.015309,0
13,2001-06-07 12:00:00,29.750000,-90.833333,341.577,7.050158,1.021075,1
14,2001-06-07 12:00:00,29.750000,-90.791667,372.277,36.756787,1.109552,1
15,2001-06-07 12:00:00,29.750000,-90.750000,356.275,19.202579,1.056969,1
16,2001-06-07 12:00:00,29.791667,-90.833333,333.068,2.067052,1.006245,1
17,2001-06-07 12:00:00,29.791667,-90.791667,364.141,31.583100,1.094970,1
18,2001-06-07 12:00:00,29.791667,-90.750000,349.578,15.090741,1.045116,1
19,2001-07-16 12:00:00,46.041667,-100.875000,139.843,8.834459,1.067434,0
20,2001-07-16 12:00:00,46.041667,-100.833333,139.142,8.591710,1.065811,0
21,2001-08-01 12:00:00,48.708333,-94.583333,142.847,0.309483,1.002171,1
22,2001-08-22 12:00:00,40.208333,-90.791667,188.764,19.888419,1.117770,0
23,2001-08-22 12:00:00,40.208333,-90.750000,201.101,31.846972,1.188161,0
24,2001-08-22 12:00:00,40.250000,-90.791667,181.610,12.275036,1.072490,0
25,2001-08-22 12:00:00,40.250000,-90.750000,194.741,25.072482,1.147773,0
26,2001-08-23 12:00:00,40.208333,-90.958333,177.475,9.302727,1.055317,0
27,2001-08-23 12:00:00,40.250000,-91.000000,170.720,0.979967,1.005773,0
28,2001-08-23 12:00:00,40.250000,-90.958333,193.171,23.778557,1.140376,0
29,2001-08-23 12:00:00,40.250000,-90.916667,182.613,13.468222,1.079625,0
30,2001-10-11 12:00:00,34.166667,-90.583333,231.801,10.620293,1.048016,0
31,2001-10-11 12:00:00,34.166667,-90.541667,233.391,11.168864,1.050260,0
32,2001-10-11 12:00:00,34.208333,-90.583333,230.814,10.293311,1.046677,0
33,2001-10-11 12:00:00,34.208333,-90.541667,232.142,10.553281,1.047626,0
34,2001-12-01 12:00:00,38.666667,-113.000000,67.086,4.118773,1.065411,0
35,2001-12-01 12:00:00,38.666667,-112.958333,67.540,3.860102,1.060617,0
36,2001-12-01 12:00:00,38.666667,-112.916667,67.717,2.945157,1.045470,0
37,2001-12-01 12:00:00,38.708333,-113.000000,66.279,2.042772,1.031801,0
38,2001-12-01 12:00:00,38.708333,-112.958333,70.812,6.217880,1.096261,0
39,2001-12-01 12:00:00,38.708333,-112.916667,69.677,4.014582,1.061140,0

#### and the files with the removed points from previous steps

In [301]:
removed1000_72h = pd.read_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv")
removed100_72h = pd.read_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv")
removed10_72h = pd.read_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv")

removed1000_48h = pd.read_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv")
removed100_48h = pd.read_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv")
removed10_48h = pd.read_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv")

removed1000_24h = pd.read_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv")
removed100_24h = pd.read_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv")
removed10_24h = pd.read_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv")

removed100_24h

Empty DataFrame
Columns: [time, lat, lon, tp, tp_minus_ari, tp_pct_of_ari, event_num]
Index: []

## Pause here!

#### now, take a look at the maps for these cases (now under "retained100")

#### if we want to remove a row because it's bad, specify the row(s) in the 100-year dataframe
#### *important note:*  change the dataframe name below based on the duration you're working on (df100_72h, or df100_48h, or df100_24h)

In [303]:
df100_24h[df100_24h.time=='2001-12-01 12:00:00']
#df100_48h[(df100_48h.time=='2014-09-09 12:00:00') & (df100_48h.event_num==2)]

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
34,2001-12-01 12:00:00,38.666667,-113.000000,67.086,4.118773,1.065411,0
35,2001-12-01 12:00:00,38.666667,-112.958333,67.540,3.860102,1.060617,0
36,2001-12-01 12:00:00,38.666667,-112.916667,67.717,2.945157,1.045470,0
37,2001-12-01 12:00:00,38.708333,-113.000000,66.279,2.042772,1.031801,0
38,2001-12-01 12:00:00,38.708333,-112.958333,70.812,6.217880,1.096261,0
39,2001-12-01 12:00:00,38.708333,-112.916667,69.677,4.014582,1.061140,0

#### *important note:* make that same change in this cell

In [305]:
####           ### which index(es) to drop?
#to_drop = [0,1,2] + list(range(10,40))
           
           #### this needs to be user-specified based on manual inspection!!
to_drop = [0,1] + list(range(34,40)) 
                                                                                
                                                                                                          
####

rows_to_drop_visual = df100_24h.loc[to_drop]
rows_to_drop_visual

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2001-01-27 12:00:00,33.458333,-109.750000,96.281,4.483180,1.048838,0
1,2001-01-27 12:00:00,33.500000,-109.750000,93.628,0.235663,1.002523,0
34,2001-12-01 12:00:00,38.666667,-113.000000,67.086,4.118773,1.065411,0
35,2001-12-01 12:00:00,38.666667,-112.958333,67.540,3.860102,1.060617,0
36,2001-12-01 12:00:00,38.666667,-112.916667,67.717,2.945157,1.045470,0
37,2001-12-01 12:00:00,38.708333,-113.000000,66.279,2.042772,1.031801,0
38,2001-12-01 12:00:00,38.708333,-112.958333,70.812,6.217880,1.096261,0
39,2001-12-01 12:00:00,38.708333,-112.916667,69.677,4.014582,1.061140,0

#### find any other points within a small radius around these (say 0.25 degrees in each direction)
#### furthermore, find points in the 100- and 10-year files on the same day and in the same radius, in all 3 durations (72,48,24)

In [306]:
latlon_buf = 0.25  ## lat/lon buffer around the centerpoint

rows_to_drop_1000_72h = removed1000_72h
rows_to_drop_100_72h = removed100_72h
rows_to_drop_10_72h = removed10_72h
rows_to_drop_1000_48h = removed1000_48h
rows_to_drop_100_48h = removed100_48h
rows_to_drop_10_48h = removed10_48h
rows_to_drop_1000_24h = removed1000_24h
rows_to_drop_100_24h = removed100_24h
rows_to_drop_10_24h = removed10_24h

for i in range(0,len(rows_to_drop_visual)):
    this_lon = rows_to_drop_visual.iloc[i].lon
    this_lat = rows_to_drop_visual.iloc[i].lat
    this_time = rows_to_drop_visual.iloc[i].time
    
    more_rows_to_drop_1000_72h = df1000_72h[(df1000_72h.time==this_time) & (df1000_72h.lon >= this_lon-latlon_buf) & (df1000_72h.lon <= this_lon+latlon_buf) & (df1000_72h.lat >= this_lat-latlon_buf) & (df1000_72h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_72h = pd.concat([rows_to_drop_1000_72h,more_rows_to_drop_1000_72h])

    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_72h = df100_72h[(df100_72h.time==this_time) & (df100_72h.lon >= this_lon-latlon_buf) & (df100_72h.lon <= this_lon+latlon_buf) & (df100_72h.lat >= this_lat-latlon_buf) & (df100_72h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_72h = df10_72h[(df10_72h.time==this_time) & (df10_72h.lon >= this_lon-latlon_buf) & (df10_72h.lon <= this_lon+latlon_buf) & (df10_72h.lat >= this_lat-latlon_buf) & (df10_72h.lat <= this_lat+latlon_buf)] 

    rows_to_drop_100_72h = pd.concat([rows_to_drop_100_72h,more_rows_to_drop_100_72h])
    rows_to_drop_10_72h = pd.concat([rows_to_drop_10_72h,more_rows_to_drop_10_72h])  

    ### repeat for 48h
    more_rows_to_drop_1000_48h = df1000_48h[(df1000_48h.time==this_time) & (df1000_48h.lon >= this_lon-latlon_buf) & (df1000_48h.lon <= this_lon+latlon_buf) & (df1000_48h.lat >= this_lat-latlon_buf) & (df1000_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_48h = pd.concat([rows_to_drop_1000_48h,more_rows_to_drop_1000_48h])
    more_rows_to_drop_100_48h = df100_48h[(df100_48h.time==this_time) & (df100_48h.lon >= this_lon-latlon_buf) & (df100_48h.lon <= this_lon+latlon_buf) & (df100_48h.lat >= this_lat-latlon_buf) & (df100_48h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_48h = df10_48h[(df10_48h.time==this_time) & (df10_48h.lon >= this_lon-latlon_buf) & (df10_48h.lon <= this_lon+latlon_buf) & (df10_48h.lat >= this_lat-latlon_buf) & (df10_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_100_48h = pd.concat([rows_to_drop_100_48h,more_rows_to_drop_100_48h])
    rows_to_drop_10_48h = pd.concat([rows_to_drop_10_48h,more_rows_to_drop_10_48h])  

    ### and 24
    more_rows_to_drop_1000_24h = df1000_24h[(df1000_24h.time==this_time) & (df1000_24h.lon >= this_lon-latlon_buf) & (df1000_24h.lon <= this_lon+latlon_buf) & (df1000_24h.lat >= this_lat-latlon_buf) & (df1000_24h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_24h = pd.concat([rows_to_drop_1000_24h,more_rows_to_drop_1000_24h])
    
    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_24h = df100_24h[(df100_24h.time==this_time) & (df100_24h.lon >= this_lon-latlon_buf) & (df100_24h.lon <= this_lon+latlon_buf) & (df100_24h.lat >= this_lat-latlon_buf) & (df100_24h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_24h = df10_24h[(df10_24h.time==this_time) & (df10_24h.lon >= this_lon-latlon_buf) & (df10_24h.lon <= this_lon+latlon_buf) & (df10_24h.lat >= this_lat-latlon_buf) & (df10_24h.lat <= this_lat+latlon_buf)] 
    
    rows_to_drop_100_24h = pd.concat([rows_to_drop_100_24h,more_rows_to_drop_100_24h])
    rows_to_drop_10_24h = pd.concat([rows_to_drop_10_24h,more_rows_to_drop_10_24h])  

#### drop duplicates
rows_to_drop_1000_72h = rows_to_drop_1000_72h.drop_duplicates()
rows_to_drop_100_72h.drop_duplicates(inplace=True)
rows_to_drop_10_72h.drop_duplicates(inplace=True)
rows_to_drop_1000_48h = rows_to_drop_1000_48h.drop_duplicates()
rows_to_drop_100_48h.drop_duplicates(inplace=True)
rows_to_drop_10_48h.drop_duplicates(inplace=True)
rows_to_drop_1000_24h = rows_to_drop_1000_24h.drop_duplicates()
rows_to_drop_100_24h.drop_duplicates(inplace=True)
rows_to_drop_10_24h.drop_duplicates(inplace=True)

rows_to_drop_100_48h

/glade/derecho/scratch/rschumac/tmp/ipykernel_5660/365401128.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  rows_to_drop_10_72h = pd.concat([rows_to_drop_10_72h,more_rows_to_drop_10_72h])
/glade/derecho/scratch/rschumac/tmp/ipykernel_5660/365401128.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  rows_to_drop_10_48h = pd.concat([rows_to_drop_10_48h,more_rows_to_drop_10_48h])
/glade/derecho/scratch/rschumac/tmp/ipykernel_5660/365401128.py:44: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  rows_to_drop_100_24h = pd.concat([rows_to_drop_100_24h,more_rows_to_drop_100_24h])
/glade/derecho/scratch/rschumac/tmp/ipykernel_5660/365401128.py:45: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  rows_to_drop_10_24h = pd.concat([rows_to_drop_10_24h,more_rows_to_drop_10_24h])
/glade/derecho/scratch/rschumac/tmp/ipykernel_5660/365401128.py:25: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  rows_to_drop_100_72h = pd.concat([rows_to_drop_100_72h,more_rows_to_drop_100_72h])
/glade/derecho/scratch/rschumac/tmp/ipykernel_5660/365401128.py:33: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  rows_to_drop_100_48h = pd.concat([rows_to_drop_100_48h,more_rows_to_drop_100_48h])

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
90,2001-12-01 12:00:00,38.666667,-113.000000,70.258995,2.465782,1.036372,0
91,2001-12-01 12:00:00,38.666667,-112.958333,71.389000,2.679446,1.038997,0
92,2001-12-01 12:00:00,38.666667,-112.916667,72.231000,1.869484,1.026570,0
93,2001-12-01 12:00:00,38.708333,-113.000000,69.874000,0.633997,1.009157,0
94,2001-12-01 12:00:00,38.708333,-112.958333,74.894000,4.558066,1.064804,0
95,2001-12-01 12:00:00,38.708333,-112.916667,74.341000,2.580897,1.035966,0

#### now drop those rows from the original dataframes. Method from here: https://www.includehelp.com/python/how-to-remove-rows-in-a-pandas-dataframe-if-the-same-row-exists-in-another-dataframe.aspx#:~:text=df1%20and%20df2.-,Remove%20rows%20in%20a%20Pandas%20dataframe%20if%20the%20same%20row,then%20drop%20the%20common%20rows.

In [307]:
df1000_72h_edit = pd.merge(df1000_72h,rows_to_drop_1000_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_72h_edit = pd.merge(df100_72h,rows_to_drop_100_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_72h_edit = pd.merge(df10_72h,rows_to_drop_10_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_72h length went from "+str(len(df1000_72h))+" to "+str(len(df1000_72h_edit)))
print("df100_72h length went from "+str(len(df100_72h))+" to "+str(len(df100_72h_edit)))
print("df10_72h length went from "+str(len(df10_72h))+" to "+str(len(df10_72h_edit)))

#### 48h
df1000_48h_edit = pd.merge(df1000_48h,rows_to_drop_1000_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_48h_edit = pd.merge(df100_48h,rows_to_drop_100_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_48h_edit = pd.merge(df10_48h,rows_to_drop_10_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_48h length went from "+str(len(df1000_48h))+" to "+str(len(df1000_48h_edit)))
print("df100_48h length went from "+str(len(df100_48h))+" to "+str(len(df100_48h_edit)))
print("df10_48h length went from "+str(len(df10_48h))+" to "+str(len(df10_48h_edit)))

### 24h
df1000_24h_edit = pd.merge(df1000_24h,rows_to_drop_1000_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_24h_edit = pd.merge(df100_24h,rows_to_drop_100_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_24h_edit = pd.merge(df10_24h,rows_to_drop_10_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_24h length went from "+str(len(df1000_24h))+" to "+str(len(df1000_24h_edit)))
print("df100_24h length went from "+str(len(df100_24h))+" to "+str(len(df100_24h_edit)))
print("df10_24h length went from "+str(len(df10_24h))+" to "+str(len(df10_24h_edit)))

df1000_72h length went from 6 to 6
df100_72h length went from 216 to 206
df10_72h length went from 22384 to 22308
df1000_48h length went from 0 to 0
df100_48h length went from 97 to 91
df10_48h length went from 10659 to 10595
df1000_24h length went from 0 to 0
df100_24h length went from 40 to 32
df10_24h length went from 3532 to 3452

In [308]:
df1000_72h_edit.to_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h_edit.csv", index=False)
df100_72h_edit.to_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h_edit.csv", index=False)
df10_72h_edit.to_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h_edit.csv", index=False)

rows_to_drop_1000_72h.to_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv", index=False)
rows_to_drop_100_72h.to_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv", index=False)
rows_to_drop_10_72h.to_csv(workdir+"/"+dataset+"/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv", index=False)
                             
#### 48h
df1000_48h_edit.to_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h_edit.csv", index=False)
df100_48h_edit.to_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h_edit.csv", index=False)
df10_48h_edit.to_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h_edit.csv", index=False)

rows_to_drop_1000_48h.to_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv", index=False)
rows_to_drop_100_48h.to_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv", index=False)
rows_to_drop_10_48h.to_csv(workdir+"/"+dataset+"/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv", index=False)  

### 24h
df1000_24h_edit.to_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h_edit.csv", index=False)
df100_24h_edit.to_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h_edit.csv", index=False)
df10_24h_edit.to_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h_edit.csv", index=False)

rows_to_drop_1000_24h.to_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv", index=False)
rows_to_drop_100_24h.to_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv", index=False)
rows_to_drop_10_24h.to_csv(workdir+"/"+dataset+"/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv", index=False)