### We're now going to repeat step 2 of the manual QC, but for 100-year events. Hopefully the worst offenders have already been removed at the 1000-year step, but we still want to look through the maps for these

#### Start at 72h for each year, then do 48, then 24

In [1]:
import pandas as pd
import os

In [43]:
duration = 24
dataset = "stage4" ### which dataset to analyze

year = 2024

workdir = "/glade/work/rschumac/precip_data/extremerain/"

#### read in the exceedance files into pandas dataframes - note that now we're reading in the cleaned, edited files

In [44]:
df100_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h_edit.csv")
df10_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h_edit.csv")
try:
    df1000_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h_edit.csv")
except:  ## if no rows, just make an empty dataframe with the right columns
    df1000_72h = pd.DataFrame(columns=df_72h.columns)

### and the 48-h ones
df100_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h_edit.csv")
df10_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h_edit.csv")
try:
    df1000_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h_edit.csv")
except:
    df1000_48h = pd.DataFrame(columns=df_48h.columns)

### and the 24-h ones
df100_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h_edit.csv")
df10_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h_edit.csv")
try:
    df1000_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h_edit.csv")
except:
    df1000_24h = pd.DataFrame(columns=df_48h.columns)

In [45]:
### change this to match the duration...
df100_24h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-02-05 12:00:00,34.583333,-119.333333,394.019040,13.600425,1.035751,0
1,2024-02-07 12:00:00,38.083333,-111.416667,98.369190,3.837655,1.040597,0
2,2024-02-07 12:00:00,38.083333,-111.375000,92.739460,3.015971,1.033614,0
3,2024-03-02 12:00:00,43.083333,-112.125000,67.450020,3.188017,1.049610,1
4,2024-03-02 12:00:00,43.125000,-112.125000,67.789055,4.543053,1.071831,1
...,...,...,...,...,...,...,...
2092,2024-11-08 12:00:00,31.916667,-99.791667,215.869600,1.468191,1.006848,0
2093,2024-11-21 12:00:00,38.625000,-123.041667,319.897770,0.100025,1.000313,0
2094,2024-11-21 12:00:00,38.625000,-123.000000,305.979300,2.053898,1.006758,0
2095,2024-11-21 12:00:00,38.666667,-123.000000,282.288570,10.451441,1.038447,0
2096,2024-11-21 12:00:00,38.666667,-122.958333,250.106840,2.607002,1.010533,0

#### and the files with the removed points, output from the automated QC algorithm

In [46]:
removed1000_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv")
removed100_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv")
removed10_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv")

removed1000_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv")
removed100_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv")
removed10_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv")

removed1000_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv")
removed100_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv")
removed10_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv")

removed100_24h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-02-07 12:00:00,37.916667,-110.750000,102.447580,28.559623,1.386526,0
1,2024-02-07 12:00:00,38.000000,-110.833333,82.387620,7.494434,1.100068,0
2,2024-02-07 12:00:00,38.000000,-110.791667,82.211070,3.887420,1.049633,0
3,2024-02-07 12:00:00,38.166667,-110.875000,86.687710,21.169165,1.323102,0
4,2024-02-07 12:00:00,38.166667,-110.833333,75.791340,5.836502,1.083432,0
...,...,...,...,...,...,...,...
195,2024-03-02 12:00:00,43.166667,-112.208333,58.460247,1.056246,1.018400,1
196,2024-03-02 12:00:00,43.041667,-112.166667,71.462875,4.330675,1.064510,1
197,2024-03-02 12:00:00,43.083333,-112.166667,70.300950,5.911946,1.091816,1
198,2024-03-02 12:00:00,43.125000,-112.166667,65.763405,5.641602,1.093836,1
199,2024-03-02 12:00:00,43.166667,-112.166667,63.883877,4.676474,1.078985,1

## Pause here!

#### now, take a look at the maps for these cases (now under "retained100")

#### if we want to remove a row because it's bad, specify the row(s) in the 100-year dataframe
#### *important note:*  change the dataframe name below based on the duration you're working on (df100_72h, or df100_48h, or df100_24h)

In [54]:
#df100_24h[df100_24h.time=='2021-12-10 12:00:00']
df100_24h[(df100_24h.time=='2024-06-28 12:00:00') & (df100_24h.event_num==0)]
#df100_24h[(df100_24h.time=='2013-06-20 12:00:00') & (df100_24h.event_num==4) & (df100_24h.lat < 44)] #.index

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
556,2024-06-28 12:00:00,37.916667,-108.791667,88.525360,4.608265,1.054914,0
557,2024-06-28 12:00:00,37.916667,-108.750000,85.107704,2.369814,1.028642,0

#### *important note:* make that same change in this cell

In [55]:
####           ### which index(es) to drop?
#to_drop = [0,1,2] + list(range(10,40))
           
           #### this needs to be user-specified based on manual inspection!!
to_drop = list(range(1,20)) + list(range(23,40)) + [73,556,557]

           
                                                                                                          
####

rows_to_drop_visual = df100_24h.loc[to_drop]
rows_to_drop_visual

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
1,2024-02-07 12:00:00,38.083333,-111.416667,98.369190,3.837655,1.040597,0
2,2024-02-07 12:00:00,38.083333,-111.375000,92.739460,3.015971,1.033614,0
3,2024-03-02 12:00:00,43.083333,-112.125000,67.450020,3.188017,1.049610,1
4,2024-03-02 12:00:00,43.125000,-112.125000,67.789055,4.543053,1.071831,1
5,2024-03-02 12:00:00,43.125000,-112.083333,71.654410,4.319011,1.064142,1
6,2024-03-02 12:00:00,43.166667,-112.125000,69.284910,5.073709,1.079016,1
7,2024-03-02 12:00:00,43.166667,-112.083333,73.947880,6.917283,1.103196,1
8,2024-03-02 12:00:00,43.375000,-111.125000,94.313360,8.994765,1.105426,1
9,2024-03-02 12:00:00,43.375000,-111.083333,93.991330,10.018941,1.119312,1
10,2024-03-02 12:00:00,43.375000,-111.041667,80.388400,1.597602,1.020276,1
11,2024-03-02 12:00:00,43.375000,-111.000000,83.288330,2.440129,1.030182,1
12,2024-03-02 12:00:00,43.375000,-110.958333,83.485970,0.478768,1.005768,1
13,2024-03-02 12:00:00,43.416667,-111.083333,89.813570,5.333164,1.063129,1
14,2024-03-02 12:00:00,43.416667,-111.041667,97.228900,9.522700,1.108575,1
15,2024-03-02 12:00:00,43.416667,-111.000000,92.187600,2.322406,1.025843,1
16,2024-03-02 12:00:00,43.666667,-110.833333,98.968380,1.051397,1.010738,1
17,2024-03-02 12:00:00,43.708333,-110.833333,107.734100,3.289302,1.031493,1
18,2024-03-02 12:00:00,43.708333,-110.791667,98.356750,1.430373,1.014757,1
19,2024-03-16 12:00:00,37.875000,-111.916667,98.710970,8.582437,1.095224,0
23,2024-04-05 12:00:00,43.208333,-116.416667,50.961975,2.143175,1.043901,0
24,2024-04-05 12:00:00,43.208333,-116.375000,53.629868,4.709468,1.096268,0
25,2024-04-05 12:00:00,43.208333,-116.333333,55.955128,5.561528,1.110362,0
26,2024-04-05 12:00:00,43.208333,-116.291667,56.407845,3.398045,1.064102,0
27,2024-04-05 12:00:00,43.208333,-116.250000,55.658005,0.514606,1.009332,0
28,2024-04-05 12:00:00,43.250000,-116.416667,54.463333,5.111133,1.103564,0
29,2024-04-05 12:00:00,43.250000,-116.375000,59.338880,9.707279,1.195587,0
30,2024-04-05 12:00:00,43.250000,-116.333333,62.291626,10.399427,1.200404,0
31,2024-04-05 12:00:00,43.250000,-116.291667,62.978070,8.545870,1.157000,0
32,2024-04-05 12:00:00,43.250000,-116.250000,61.842580,5.327580,1.094268,0
33,2024-04-05 12:00:00,43.250000,-116.208333,58.118440,0.460439,1.007986,0
34,2024-04-05 12:00:00,43.291667,-116.416667,50.567654,0.529654,1.010585,0
35,2024-04-05 12:00:00,43.291667,-116.375000,57.357162,5.871363,1.114039,0
36,2024-04-05 12:00:00,43.291667,-116.333333,60.030582,6.360383,1.118509,0
37,2024-04-05 12:00:00,43.291667,-116.291667,60.924232,5.399833,1.097252,0
38,2024-04-05 12:00:00,43.291667,-116.250000,61.357723,4.868123,1.086177,0
39,2024-04-05 12:00:00,43.291667,-116.208333,57.379807,0.204406,1.003575,0
73,2024-05-04 12:00:00,34.000000,-84.000000,189.854200,2.500056,1.013344,0
556,2024-06-28 12:00:00,37.916667,-108.791667,88.525360,4.608265,1.054914,0
557,2024-06-28 12:00:00,37.916667,-108.750000,85.107704,2.369814,1.028642,0

#### find any other points within a small radius around these (say 0.10 degrees in each direction)
#### furthermore, find points in the 100- and 10-year files on the same day and in the same radius, in all 3 durations (72,48,24)

In [56]:
latlon_buf = 0.10  ## lat/lon buffer around the centerpoint

rows_to_drop_1000_72h = removed1000_72h
rows_to_drop_100_72h = removed100_72h
rows_to_drop_10_72h = removed10_72h
rows_to_drop_1000_48h = removed1000_48h
rows_to_drop_100_48h = removed100_48h
rows_to_drop_10_48h = removed10_48h
rows_to_drop_1000_24h = removed1000_24h
rows_to_drop_100_24h = removed100_24h
rows_to_drop_10_24h = removed10_24h

for i in range(0,len(rows_to_drop_visual)):
    this_lon = rows_to_drop_visual.iloc[i].lon
    this_lat = rows_to_drop_visual.iloc[i].lat
    this_time = rows_to_drop_visual.iloc[i].time
    
    more_rows_to_drop_1000_72h = df1000_72h[(df1000_72h.time==this_time) & (df1000_72h.lon >= this_lon-latlon_buf) & (df1000_72h.lon <= this_lon+latlon_buf) & (df1000_72h.lat >= this_lat-latlon_buf) & (df1000_72h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_72h = pd.concat([rows_to_drop_1000_72h,more_rows_to_drop_1000_72h])

    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_72h = df100_72h[(df100_72h.time==this_time) & (df100_72h.lon >= this_lon-latlon_buf) & (df100_72h.lon <= this_lon+latlon_buf) & (df100_72h.lat >= this_lat-latlon_buf) & (df100_72h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_72h = df10_72h[(df10_72h.time==this_time) & (df10_72h.lon >= this_lon-latlon_buf) & (df10_72h.lon <= this_lon+latlon_buf) & (df10_72h.lat >= this_lat-latlon_buf) & (df10_72h.lat <= this_lat+latlon_buf)] 

    rows_to_drop_100_72h = pd.concat([rows_to_drop_100_72h,more_rows_to_drop_100_72h])
    rows_to_drop_10_72h = pd.concat([rows_to_drop_10_72h,more_rows_to_drop_10_72h])  

    ### repeat for 48h
    more_rows_to_drop_1000_48h = df1000_48h[(df1000_48h.time==this_time) & (df1000_48h.lon >= this_lon-latlon_buf) & (df1000_48h.lon <= this_lon+latlon_buf) & (df1000_48h.lat >= this_lat-latlon_buf) & (df1000_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_48h = pd.concat([rows_to_drop_1000_48h,more_rows_to_drop_1000_48h])
    more_rows_to_drop_100_48h = df100_48h[(df100_48h.time==this_time) & (df100_48h.lon >= this_lon-latlon_buf) & (df100_48h.lon <= this_lon+latlon_buf) & (df100_48h.lat >= this_lat-latlon_buf) & (df100_48h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_48h = df10_48h[(df10_48h.time==this_time) & (df10_48h.lon >= this_lon-latlon_buf) & (df10_48h.lon <= this_lon+latlon_buf) & (df10_48h.lat >= this_lat-latlon_buf) & (df10_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_100_48h = pd.concat([rows_to_drop_100_48h,more_rows_to_drop_100_48h])
    rows_to_drop_10_48h = pd.concat([rows_to_drop_10_48h,more_rows_to_drop_10_48h])  

    ### and 24
    more_rows_to_drop_1000_24h = df1000_24h[(df1000_24h.time==this_time) & (df1000_24h.lon >= this_lon-latlon_buf) & (df1000_24h.lon <= this_lon+latlon_buf) & (df1000_24h.lat >= this_lat-latlon_buf) & (df1000_24h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_24h = pd.concat([rows_to_drop_1000_24h,more_rows_to_drop_1000_24h])
    
    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_24h = df100_24h[(df100_24h.time==this_time) & (df100_24h.lon >= this_lon-latlon_buf) & (df100_24h.lon <= this_lon+latlon_buf) & (df100_24h.lat >= this_lat-latlon_buf) & (df100_24h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_24h = df10_24h[(df10_24h.time==this_time) & (df10_24h.lon >= this_lon-latlon_buf) & (df10_24h.lon <= this_lon+latlon_buf) & (df10_24h.lat >= this_lat-latlon_buf) & (df10_24h.lat <= this_lat+latlon_buf)] 
    
    rows_to_drop_100_24h = pd.concat([rows_to_drop_100_24h,more_rows_to_drop_100_24h])
    rows_to_drop_10_24h = pd.concat([rows_to_drop_10_24h,more_rows_to_drop_10_24h])  

#### drop duplicates
rows_to_drop_1000_72h = rows_to_drop_1000_72h.drop_duplicates()
rows_to_drop_100_72h.drop_duplicates(inplace=True)
rows_to_drop_10_72h.drop_duplicates(inplace=True)
rows_to_drop_1000_48h = rows_to_drop_1000_48h.drop_duplicates()
rows_to_drop_100_48h.drop_duplicates(inplace=True)
rows_to_drop_10_48h.drop_duplicates(inplace=True)
rows_to_drop_1000_24h = rows_to_drop_1000_24h.drop_duplicates()
rows_to_drop_100_24h.drop_duplicates(inplace=True)
rows_to_drop_10_24h.drop_duplicates(inplace=True)

rows_to_drop_100_24h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-02-07 12:00:00,37.916667,-110.750000,102.447580,28.559623,1.386526,0
1,2024-02-07 12:00:00,38.000000,-110.833333,82.387620,7.494434,1.100068,0
2,2024-02-07 12:00:00,38.000000,-110.791667,82.211070,3.887420,1.049633,0
3,2024-02-07 12:00:00,38.166667,-110.875000,86.687710,21.169165,1.323102,0
4,2024-02-07 12:00:00,38.166667,-110.833333,75.791340,5.836502,1.083432,0
...,...,...,...,...,...,...,...
33,2024-04-05 12:00:00,43.250000,-116.208333,58.118440,0.460439,1.007986,0
39,2024-04-05 12:00:00,43.291667,-116.208333,57.379807,0.204406,1.003575,0
73,2024-05-04 12:00:00,34.000000,-84.000000,189.854200,2.500056,1.013344,0
556,2024-06-28 12:00:00,37.916667,-108.791667,88.525360,4.608265,1.054914,0
557,2024-06-28 12:00:00,37.916667,-108.750000,85.107704,2.369814,1.028642,0

#### now drop those rows from the original dataframes. Method from here: https://www.includehelp.com/python/how-to-remove-rows-in-a-pandas-dataframe-if-the-same-row-exists-in-another-dataframe.aspx#:~:text=df1%20and%20df2.-,Remove%20rows%20in%20a%20Pandas%20dataframe%20if%20the%20same%20row,then%20drop%20the%20common%20rows.

In [57]:
df1000_72h_edit = pd.merge(df1000_72h,rows_to_drop_1000_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_72h_edit = pd.merge(df100_72h,rows_to_drop_100_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_72h_edit = pd.merge(df10_72h,rows_to_drop_10_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_72h length went from "+str(len(df1000_72h))+" to "+str(len(df1000_72h_edit)))
print("df100_72h length went from "+str(len(df100_72h))+" to "+str(len(df100_72h_edit)))
print("df10_72h length went from "+str(len(df10_72h))+" to "+str(len(df10_72h_edit)))

#### 48h
df1000_48h_edit = pd.merge(df1000_48h,rows_to_drop_1000_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_48h_edit = pd.merge(df100_48h,rows_to_drop_100_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_48h_edit = pd.merge(df10_48h,rows_to_drop_10_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_48h length went from "+str(len(df1000_48h))+" to "+str(len(df1000_48h_edit)))
print("df100_48h length went from "+str(len(df100_48h))+" to "+str(len(df100_48h_edit)))
print("df10_48h length went from "+str(len(df10_48h))+" to "+str(len(df10_48h_edit)))

### 24h
df1000_24h_edit = pd.merge(df1000_24h,rows_to_drop_1000_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_24h_edit = pd.merge(df100_24h,rows_to_drop_100_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_24h_edit = pd.merge(df10_24h,rows_to_drop_10_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_24h length went from "+str(len(df1000_24h))+" to "+str(len(df1000_24h_edit)))
print("df100_24h length went from "+str(len(df100_24h))+" to "+str(len(df100_24h_edit)))
print("df10_24h length went from "+str(len(df10_24h))+" to "+str(len(df10_24h_edit)))

df1000_72h length went from 877 to 877
df100_72h length went from 8942 to 8942
df10_72h length went from 103061 to 102965
df1000_48h length went from 456 to 456
df100_48h length went from 5370 to 5370
df10_48h length went from 66054 to 65906
df1000_24h length went from 31 to 31
df100_24h length went from 2097 to 2057
df10_24h length went from 28267 to 28078

In [58]:
df1000_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h_edit.csv", index=False)
df100_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h_edit.csv", index=False)
df10_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h_edit.csv", index=False)

rows_to_drop_1000_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv", index=False)
rows_to_drop_100_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv", index=False)
rows_to_drop_10_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv", index=False)
                             
#### 48h
df1000_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h_edit.csv", index=False)
df100_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h_edit.csv", index=False)
df10_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h_edit.csv", index=False)

rows_to_drop_1000_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv", index=False)
rows_to_drop_100_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv", index=False)
rows_to_drop_10_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv", index=False)  

### 24h
df1000_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h_edit.csv", index=False)
df100_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h_edit.csv", index=False)
df10_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h_edit.csv", index=False)

rows_to_drop_1000_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv", index=False)
rows_to_drop_100_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv", index=False)
rows_to_drop_10_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv", index=False)

In [476]:
rows_to_drop_100_24h[rows_to_drop_100_24h.time=='2015-06-18 12:00:00']

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
41,2015-06-18 12:00:00,32.416667,-93.708333,335.54080,70.602225,1.266485,0
42,2015-06-18 12:00:00,32.416667,-93.666667,328.16626,63.583391,1.240316,0
43,2015-06-18 12:00:00,32.458333,-93.708333,270.47787,6.656939,1.025233,0
44,2015-06-18 12:00:00,32.458333,-93.666667,291.70718,28.138362,1.106759,0
45,2015-06-18 12:00:00,32.458333,-93.625000,273.54907,10.386720,1.039469,0
304,2015-06-18 12:00:00,32.583333,-93.666667,363.34335,102.109355,1.390873,0
305,2015-06-18 12:00:00,32.708333,-93.625000,266.50460,6.920686,1.026661,0

In [478]:
df100_24h_edit[df100_24h_edit.time=='2015-06-18 12:00:00']

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
373,2015-06-18 12:00:00,33.625000,-97.708333,239.86478,8.648562,1.037405,1
374,2015-06-18 12:00:00,33.625000,-97.666667,234.47488,1.734672,1.007453,1
375,2015-06-18 12:00:00,33.666667,-97.750000,234.71384,5.250224,1.022880,1
376,2015-06-18 12:00:00,33.666667,-97.708333,255.22235,24.082338,1.104189,1
377,2015-06-18 12:00:00,33.666667,-97.666667,253.07323,20.206015,1.086771,1
...,...,...,...,...,...,...,...
491,2015-06-18 12:00:00,34.458333,-97.500000,237.95126,12.466564,1.055288,1
492,2015-06-18 12:00:00,34.458333,-97.250000,229.14935,0.437308,1.001912,1
493,2015-06-18 12:00:00,34.458333,-97.208333,239.00745,9.847304,1.042971,1
494,2015-06-18 12:00:00,34.458333,-97.166667,243.54506,14.234418,1.062075,1
495,2015-06-18 12:00:00,34.458333,-97.125000,237.08807,7.830004,1.034154,1